root_dir: /opt/kubengine
domain: kubengine.io
tls:
  root_dir: /opt/kubengine/config/certs
auth:
  jwt:
    algorithm: HS256
  token:
    expire_minutes: 30
    renew_threshold_minutes: 5
  users:
    admin:
      password_hash: $2b$12$8Ccom3XJXVFY079nrPO6IeaV4ksBRc4GA0b6bDrCFF2uUdKOSn2Wu
      ak: AK6C0802BC
      sk_hash: $2b$12$mQH5.6gmnbXMMY8XdeW0L.hLpEvFZaTi4elfr756sNsLgC8bl0QpC
cluster:
  nodes:
    - 172.31.57.23
    - 172.31.57.22
    - 172.31.57.21
  hostnames:
    172.31.57.23: kubengine3
    172.31.57.22: kubengine2
    172.31.57.21: kubengine1

kubernetes:
  master:
    ip: 172.31.57.23
    schedulable: True
  worker:
    ips:
      - 172.31.57.22
      - 172.31.57.21
  cidr:
    pod: 10.96.0.0/16
    service: 10.97.0.0/16
  loadbalancer:
    ip-pools:
      - 172.31.57.30-172.31.57.40
